name: Compile Domain Lists from JSON
on:
  push:
    paths:
      - "json/*.json"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Create output directories
        run: |
          mkdir -p raw
          mkdir -p srs

      - name: Convert JSON to TXT
        run: python convert_json_to_txt.py

      - name: Install sing-box
        run: |
          bash <(curl -fsSL https://sing-box.app/deb-install.sh)

      - name: Compile JSON to SRS
        run: |
          for file in json/*.json; do
            filename=$(basename "$file" .json)
            sing-box rule-set compile "$file" -o "srs/${filename}.srs"
          done

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add raw/*.txt srs/*.srs
          git commit -m "chore: auto-compile domain lists and rule-sets" || exit 0
          git push
